# Site settings
title: Academic Page
title_separator: ""
email: eric.regis[at]yale.edu
description: >- # this means to ignore newlines until "baseurl:"
  Graduate student in Biophysics at Yale University.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eregis.github.io" # Replace with your actual GitHub Pages URL
github_username: eregis # Replace with your actual GitHub username

# Author information
author: Eric Regis
description: Physics graduate student at Yale University

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  posts:
    output: true
  cv:
    output: true
  notes:
    output: true

# Markdown settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: true

# Social media (add or remove as needed)
social:
  - platform: linkedin
    user_url: https://www.linkedin.com/in/eric-regis-ab8a3b278/
  - platform: github
    user_url: https://github.com/eregis

# Google Analytics
google_analytics: G-M8TE1MHJ0G